---
title: "Title"
author: "Ishani Makwana, Henry Hirsch and Ei Tanaka"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
rm(list=ls())
library(readr)
library(usmap)
library(ggplot2)
```

```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

## Introduction (need edited)
**(need edited)**

```{r init_data}
# Importing a geographic health disparities data set

urlfile = 'https://raw.githubusercontent.com/eitanaka/DATS6101_Project1_Team2/main/dataset/geographic_health_disparities.csv'

geo_health_df <- read_csv(url(urlfile))
```

## Summary Statistics(need edited)
```{r}
# Create data frame by state
data_by_state <- split(geo_health_df, geo_health_df$StateAbbr)
```

### Depression by state(need edited)
```{r EDA_basicstats_Depression}
summary_by_state <- lapply(data_by_state, function(x) summary(x$Data_Value.DEPRESSION))
head(summary_by_state,3)
tail(summary_by_state,3)

sd_by_state <- lapply(data_by_state, function(x) sd(x$Data_Value.DEPRESSION))
head(summary_by_state,3)
tail(summary_by_state,3)

# Convert mean_by_state to a data frame
mean_by_state_DEPRESSION <- lapply(data_by_state, function(x) mean(x$Data_Value.DEPRESSION))
mean_df_DEPRESSION <- data.frame(State = names(mean_by_state_DEPRESSION), Mean_Depression = unlist(mean_by_state_DEPRESSION))

# Create a bar chart of the mean depression values by state
barplot(mean_df_DEPRESSION$Mean_Depression, names.arg = mean_df_DEPRESSION$State, xlab = "State", ylab = "Mean Depression Value", col = "red", main = "Mean Depression Values by State")

# Create a new maps object
mean_df_DEPRESSION["fips"] <- fips(mean_df_DEPRESSION$State)

plot_usmap(data=mean_df_DEPRESSION, values="Mean_Depression", labels = TRUE) +
  scale_fill_continuous(low = "white", high = "red", guide = FALSE) +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  ggtitle("Mean_Depression by State") +
  guides(fill = guide_colorbar(title = "Mean_Depression", 
                                title.position = "top", 
                                title.hjust = 0.5, 
                                label.position = "left",
                                label.hjust = 0.5))
```

### Mental health by state(need edited)
```{r echo=T, eval=T, include=T, results='markup'}
summary_by_state <- lapply(data_by_state, function(x) summary(x$Data_Value.MHLTH))
head(summary_by_state,3)
tail(summary_by_state,3)

sd_by_state <- lapply(data_by_state, function(x) sd(x$Data_Value.MHLTH))
head(sd_by_state,3)
tail(sd_by_state,3)

# Convert mean_by_state to a data frame
mean_by_state_MHLTH <- lapply(data_by_state, function(x) mean(x$Data_Value.MHLTH))
mean_df_MHLTH <- data.frame(State = names(mean_by_state_MHLTH), Mean_MHLTH = unlist(mean_by_state_MHLTH))

barplot(mean_df_MHLTH$Mean_MHLTH, names.arg = mean_df_MHLTH$State, xlab = "State", ylab = "Mean Mental Value", col = "green", main = "Mean mental Values by State")

# Create a new maps object
mean_df_MHLTH["fips"] <- fips(mean_df_MHLTH$State)

plot_usmap(data=mean_df_MHLTH, values="Mean_MHLTH", labels = TRUE) +
  scale_fill_continuous(low = "white", high = "green", guide = FALSE) +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  ggtitle("Mean_LPA by State") +
  guides(fill = guide_colorbar(title = " Mean_MHLTH", 
                                title.position = "top", 
                                title.hjust = 0.5, 
                                label.position = "left",
                                label.hjust = 0.5))
```

### Sleep by state(need edited)
```{r echo=T, eval=T, include=T, results='markup'}
summary_by_state <- lapply(data_by_state, function(x) summary(x$Data_Value.SLEEP))
head(summary_by_state,3)
tail(summary_by_state,3)

sd_by_state <- lapply(data_by_state, function(x) sd(x$Data_Value.SLEEP))
head(sd_by_state,3)
tail(sd_by_state,3)

# Convert mean_by_state to a data frame
mean_by_state_SLEEP <- lapply(data_by_state, function(x) mean(x$Data_Value.SLEEP))
mean_df_SLEEP <- data.frame(State = names(mean_by_state_SLEEP), Mean_Sleep = unlist(mean_by_state_SLEEP))

# Create a bar chart of the mean depression values by state
barplot(mean_df_SLEEP$Mean_Sleep, names.arg = mean_df_SLEEP$State, xlab = "State", ylab = "Mean SLEEP Value", col = "blue", main = "Mean SLEEP Values by State")

mean_df_SLEEP["fips"] <- fips(mean_df_SLEEP$State)

# Create a new maps object
plot_usmap(data=mean_df_SLEEP, values="Mean_Sleep", labels = TRUE) +
  scale_fill_continuous(low = "white", high = "blue", guide = FALSE) +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0)) +
  ggtitle("Mean Sleep by State") +
  guides(fill = guide_colorbar(title = "Mean Sleep", 
                                title.position = "top", 
                                title.hjust = 0.5, 
                                label.position = "left",
                                label.hjust = 0.5))


# THIS IS HENRY'S COMMENT FOR THE NEW BRANCH
```

```

### Corelation between each disease by state
```{r}
# Compute the correlation matrix
# Merge the first two data frames by the "id" column
mean_df <- merge(merge(mean_df_DEPRESSION, mean_df_MHLTH, by=c("State", "fips")), mean_df_SLEEP, by=c("State", "fips"))

head(mean_df)
```

